name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ESP_IDF_SDKCONFIG_DEFAULTS: "${{ github.workspace }}/.github/configs/sdkconfig.defaults"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: riscv32imc-esp-espidf
            idf-version: release/v4.4
            rustflags: "-C default-linker-libraries"
            build-options: --example ble5_*
          - target: riscv32imc-esp-espidf
            idf-version: release/v5.0
            rustflags: "-C default-linker-libraries --cfg espidf_time64"
          - target: riscv32imc-esp-espidf
            idf-version: v5.1.1
            rustflags: "-C default-linker-libraries --cfg espidf_time64"
          - target: riscv32imac-esp-espidf
            idf-version: v5.1.1
            rustflags: "-C default-linker-libraries --cfg espidf_time64"
            mcu: esp32c6
          - target: xtensa-esp32-espidf
            idf-version: release/v4.4
            build-options: --example ble_*
          - target: xtensa-esp32-espidf
            idf-version: release/v5.0
            rustflags: "--cfg espidf_time64"
          - target: xtensa-esp32-espidf
            idf-version: v5.1.1
            rustflags: "--cfg espidf_time64"

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: true
      - name: Setup | MCU
        if: ${{ matrix.mcu }}
        run: echo "MCU=${{ matrix.mcu }}" >> "$GITHUB_ENV"
      - name: Build
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.rustflags }}"
        run: cargo build --target ${{ matrix.target }} ${{ matrix.build-options }}
      - name: Fmt check
        run: cargo fmt --check
      - name: Clippy check
        env:
          ESP_IDF_VERSION: ${{ matrix.idf-version }}
          RUSTFLAGS: "${{ matrix.rustflags }}"
        run: cargo clippy --target ${{ matrix.target }} -- -D clippy::all
